name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
       
jobs:               
  build:
    strategy:
      matrix:
        arch : [x86,x64,amd64_arm64]
        include:
         - arch : x86
           bindings : -DZ3_BUILD_PYTHON_BINDINGS=True
         - arch : x64
           cmd1 : 'julia -e "using Pkg; Pkg.add(PackageSpec(name=\"libcxxwrap_julia_jll\", version=\"0.7.0\"))"'
           cmd2 : 'julia -e "using libcxxwrap_julia_jll; print(dirname(libcxxwrap_julia_jll.libcxxwrap_julia_path))" > tmp.env'
           cmd3 : 'set /P JlCxxDir=<tmp.env'
           bindings: '-DJlCxx_DIR=%JlCxxDir%\..\lib\cmake\JlCxx $(cmakeJava) $(cmakeNet) $(cmakePy) -DCMAKE_BUILD_TYPE=RelWithDebInfo'
         - arch : amd64_arm64
           bindings: -DZ3_BUILD_PYTHON_BINDINGS=True

    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create build directory
        run: md build
      - name: Build
        run:  cd build
      - name: cmd1
        if: ${{ matrix.cmd1 }}
        run: cmd1
      - name: cmd2
        if: ${{ matrix.cmd2 }}
        run: cmd2
      - name: cmd3
        if: ${{ matrix.cmd3 }}
        run: cmd3        
      - name: vscmd
        run: call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}
      - name: configure
        run: cmake ${{ matrix.bindings }} -G "NMake Makefiles" ../
      - name: make
        run: nmake
